In [54]:
import numpy as np # import numpy & Assign alias np

In [55]:
a = np.array([1,2,3,4,5])    # Create Simple Array
print(a)

[1 2 3 4 5]


In [63]:
print("Shape of a :",format(a.shape))  # Retrurn the shape of array

Shape of a : (5,)


In [61]:
print("Size : ",format(a.size))   # Return Size of Array
print(f"dtype {a.dtype}")         # Return Datatype of Array
print(f"itemsize {a.itemsize}")   # Return Itemsize of Array
print(f"data {a.data}")           # Return data of Array

Size :  5
dtype int64
itemsize 8
data <memory at 0x7fc9a33fb640>


In [62]:
print(a[1:3])   # return array from index no 1 to 3

[2 3]


In [2]:
a=np.array([1,2,3,4,5,6])       # create Single Array
b=np.array([[9,8,7],[6,5,4]])   # create Two Dimension Array
print(a)                        # print Array
print(b)

[1 2 3 4 5 6]
[[9 8 7]
 [6 5 4]]


In [7]:
slicedArr=a[:4]      # Slice the Array
print(slicedArr)

[1 2 3 4]


In [8]:
print(a.sum())   # Return the Sum of Array

21


In [9]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])    # Used for Matrix Multiplication for 2 Two Dimension Array
mul=np.dot(m1,m2)             # 1,2 * 5,6
print(mul)                    # 3,4   7,8

[[19 22]
 [43 50]]


In [10]:
addM=np.add(m1,m2)     # Used for Addition of Two Array
print(addM)

[[ 6  8]
 [10 12]]


In [11]:
subM=np.subtract(m2,m1)     # Used for Substraction of Two Array
print(subM)

[[4 4]
 [4 4]]


In [13]:
m3=np.array([1,2,3,4,5,6,7,8,9])
re=m3.reshape(3,3)                 # Used for Reshape the Array into 3*3 
print(re)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print("Max m3 is : ",m3.max())              # return Maximum Value from m3 Array
print("Min m3 is : ",m3.min())              # return Minimum Value from m3 Array
print("Max in row is : ",re.max(axis=1))    # return Maximum value from re Array as Row wise
print("Min in col is : ",re.min(axis=0))    # return Minimum value from re Array as Column wise

Max m3 is :  9
Min m3 is :  1
Max in row is :  [3 6 9]
Min in col is :  [1 2 3]


In [16]:
m4=np.array([[4,9,25],[36,49,64]])
print(np.sqrt(m4))                    # return Squre Root of Array m4
print(np.std(m4))                     # return Standerd Deviation of Array m4

[[2. 3. 5.]
 [6. 7. 8.]]
21.16141667175323


In [22]:
NAr=np.array([[1,2],[3,4]])
print(np.vstack(NAr))    # Used to print the array in vertically 
print(np.hstack(NAr))    # Used to print the array in Horizontally

[[1 2]
 [3 4]]
[1 2 3 4]


In [21]:
arr=np.arange(0,20,2,float)         # Used to assign array from 0 to 20 in Between the gap is 2 as a Float  
print(arr)
print("Data Type : ",arr.dtype)     # Used to Display the Datatype of Array

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
Data Type :  float64


In [28]:
arr1=np.linspace(0,20,3)   # Create Array from 0 to 20 with 3 Values
print(arr1)

[ 0. 10. 20.]


In [48]:
NAr=np.array([[1,2],[3,4]])      # Transform the Array
h=np.vstack(NAr)                 # 1,2   -->  1,3
ht=h.T                           # 3,4        2,4
print(ht)

[[1 3]
 [2 4]]


In [51]:
for i in np.nditer(ht):    # Print the Array Element One by One
    print("Ele : ",i)

Ele :  1
Ele :  2
Ele :  3
Ele :  4


In [52]:
arr=np.array([23,32,34,67])
print("Sqrt : ",np.sqrt(arr))    # return Squre root of each Array
print("Exp : ",np.exp(arr))      # return Exponentials of each element
print("Sin : ",np.sin(arr))      # return sin of each element
print("Cos : ",np.cos(arr))      # return cosine of each element
print("Log : ",np.log(arr))      # return logarithm of each element
print("Sum : ",np.sum(arr))      # return sum of elements in array
print("Std : ",np.std(arr))      # return standard deviation of array

Sqrt :  [4.79583152 5.65685425 5.83095189 8.18535277]
Exp :  [9.74480345e+09 7.89629602e+13 5.83461743e+14 1.25236317e+29]
Sin :  [-0.8462204   0.55142668  0.52908269 -0.85551998]
Cos :  [-0.53283302  0.83422336 -0.84857027 -0.5177698 ]
Log :  [3.13549422 3.4657359  3.52636052 4.20469262]
Sum :  156
Std :  16.688319268278637


In [53]:
from scipy import stats as st
print("mean:",np.mean(arr))     # return mean of array
print("mean:",np.median(arr))   # return median of array
print("mean:",st.mode(arr))     # return mode of array

mean: 39.0
mean: 33.0
mean: ModeResult(mode=array([23]), count=array([1]))
